---
- name: Setup cybersecurity enviroment
  hosts: machines
  connection: local
  become: yes

  tasks:
    - name: Check the state of the system apt cache
      apt:
        update_cache: yes
        cache_valid_time: 1800 #Only check if cache hasnt been checked in last 30 minutes
    - name: Check Snap installation
      ansible.builtin.stat: 
        path: /usr/bin/snap
      register: snap_check
    - name: Install general apt packages
      apt: 
        pkg: 
          - tmux
          - nano
          - sed
          - git
          - tree
          - konsole
        state: "{{app_state | default('present')}}" # Defaults to "present" instead of updating
    - name: Install python and deps using apt
      apt: 
        pkg: 
         - pipx
         - python3
         - python3-pip
         - python3-venv 
        state: "{{app_state | default('present')}}"
    - name: Install chepy globablly using pipx
      ansible.builtin.command: pipx install chepy
      environment: 
        # These variables force pipx to install globally instead of in /root/.local/
        PIPX_HOME: /opt/pipx
        PIPX_BIN_DIR: /usr/local/bin
      args:
        # This makes the task idempotent: it skips running if chepy already exists
        creates: /usr/local/bin/chepy
    - name: Install password cracking tools using apt
      apt: 
        pkg:
          - hashcat
          # Install both ophcrack gui and ophcrack-cli
          - ophcrack 
          - ophcrack-cli
          - hashid
        state: "{{app_state | default('present')}}"
    - name: Install password cracking tools using snap
      community.general.snap:
        name:
          - john-the-ripper
      when:
        - snap_check.stat.exists
    - name: Install network tools uisng apt
      apt: 
        pkg:
          - wireshark
          - nmap
        state: "{{app_state | default('present')}}"
    - name: Install network tools using snap
      community.general.snap:
        name:
          - amass
      when:
        - snap_check.stat.exists
    - name: Install log analysis tools using apt
      apt: 
        pkg:
          - binutils
          - libimage-exiftool-perl
        state: "{{app_state | default('present')}}"
      
      
